### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by gftd** [yoheikikuta/senet-keras#4] opened 2018-09-25 03:25 UTC
I train senet model like this:

`senet =SEResNeXt.SEResNeXt(224,12).model`
`adam = tensorflow.keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, decay=1e-6)`
` senet.compile(loss='categorical_crossentropy',optimizer=adam, metrics=['accuracy'])`
` filepath="model_val/weights-improvement-{epoch:02d}-{acc:.2f}.hdf5"`
` checkpoint = ModelCheckpoint(filepath, monitor='acc', verbose=1, save_best_only=True, mode='max')`
` senet.fit(X, Y ,epochs=200, batch_size=2,callbacks=[checkpoint ])`

When I try to load trained model, i got this : 

`    model = load_model('model_val/weights-improvement-32-0.95.hdf5')
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/models.py", line 314, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 696, in from_config
    printable_module_name='function in Lambda layer')
  File "/home/tensorflow04/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 156, in deserialize_keras_object
    fn = module_objects.get(function_name)
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by yoheikikuta** [comment] 2018-09-27 14:37
@gftd 
It seems your environment is different from mine, I cannot reproduce your error.
And I just checked a trained model loading in https://github.com/yoheikikuta/senet-keras/blob/master/evaluate-cifar10.ipynb; in the notebook I loaded the model as follows:

```
model = SEResNeXt(size=size).model
model.load_weights("trained_model/SEResNeXt.h5", by_name=True)
```

I'm not sure whether it is helpful to you, but maybe model instantiation -> load_weight step is required.

**Comment by xinyuegtxy** [comment] 2018-12-25 07:39
could you give us the link to download the pretrained senet model of keras version?

**Comment by yoheikikuta** [comment] 2019-03-12 10:53
Since I provided a trained model, I'll close this issue.

**Closed by yoheikikuta** 2019-03-12 10:53 UTC
